app_name: "Gemini RAG for Nutrion"

gemini:
  # llm_model: "meta-llama/llama-3.1-8b-instruct:free"
  llm_model: "meta-llama/llama-3.3-70b-instruct:free"
  embedding_model: "openai/text-embedding-3-small"

data_ingestion:
  document_sources:

    - type: "website"
      urls:
        - "https://www.who.int/health-topics/nutrition"
        - "https://www.who.int/news-room/fact-sheets/detail/healthy-diet"
        - "https://www.hsph.harvard.edu/nutritionsource/what-is-protein/"
        - "https://www.hsph.harvard.edu/nutritionsource/healthy-eating-plate/"

    - type: "pdf"
      path: "./data/pdfs/"

    - type: "pdf"
      path: "./data/compliance/"

    # - type: "markdown"
    #   path: "./data/web/"
  chunking:
    chunk_size: 1000
    chunk_overlap: 200
    
  vector_store:
    # type: "chromadb"
    # persist_directory: "./rag/chroma_db"
    # collection_name: "nutribench_rag"

    type: "supabase"
    supabase_url: ""
    supabase_key: ""

rag:
  retrieval_k: 8
  chain_type: "stuff"
